PCDACO/PCDACO-BE

src/UseCases/UC_Manufacturer/CreateManufacturer.cs
=> fix: create manufacturer

test/UseCases.UnitTests/TestBases/DatabaseTestBase.cs, test/UseCases.UnitTests/TestBases/SharedTestColleciton.cs, test/UseCases.UnitTests/UC_Amenity/Commands/CreateAmenityTest.cs, test/UseCases.UnitTests/UC_Amenity/Commands/DeleteAmenityTest.cs, test/UseCases.UnitTests/UC_Amenity/Commands/UpdateAmenityTest.cs, test/UseCases.UnitTests/UC_Amenity/Queries/GetAmenitiesTest.cs, test/UseCases.UnitTests/UC_Amenity/Queries/GetAmenityByIdTest.cs, test/UseCases.UnitTests/UC_Booking/Commands/CreateBookingTest.cs, test/UseCases.UnitTests/UC_Car/Commands/CreateCarTest.cs, test/UseCases.UnitTests/UC_Car/Commands/DeleteCarTest.cs, test/UseCases.UnitTests/UC_Manufacturer/Commands/CreateManufacturerTest.cs, test/UseCases.UnitTests/UC_Manufacturer/Commands/DeleteManufacturerTest.cs, test/UseCases.UnitTests/UC_Manufacturer/Commands/UpdateManufacturerTest.cs, test/UseCases.UnitTests/UC_Manufacturer/Queries/GetManufacturersTest.cs, test/UseCases.UnitTests/UC_User/Commands/CreateAdminTest.cs, test/UseCases.UnitTests/UC_User/Commands/LoginTest.cs, test/UseCases.UnitTests/UC_User/Commands/SignUpTest.cs, test/UseCases.UnitTests/UseCases.UnitTests.csproj
solve timed out problem, reduce from 150s to 30s execution time
=> fix: group all test into 1 container, achive fast execution time

src/API/Endpoints/BookingStatusEndpoints/DeleteBookingStatusEndpoint.cs, src/UseCases/UC_BookingStatus/Commands/DeleteBookingStatus.cs
fix: group all test into 1 container, achive fast execution time
=> feat: delete booking status

src/API/Endpoints/BookingStatusEndpoints/GetBookingStatusByIdEndpoint.cs, src/UseCases/UC_BookingStatus/Queries/GetBookingStatusById.cs
fix: group all test into 1 container, achive fast execution time
=> feat: get booking status by id

src/API/Endpoints/BookingStatusEndpoints/GetBookingStatusesEndpoint.cs, src/UseCases/UC_BookingStatus/Queries/GetBookingStatusById.cs, src/UseCases/UC_BookingStatus/Queries/GetBookingStatuses.cs
fix: group all test into 1 container, achive fast execution time
=> feat: get booking statuses

src/API/AppConfig.cs
feat: get cars(with more filters)
=> feat: allow cors

src/API/Endpoints/CarEndpoints/GetCarsForAdminEndpoint.cs, src/UseCases/UC_Car/Queries/GetCarsForAdmin.cs
=> feat: get all cars for admin

src/API/Endpoints/UserRoleEndpoints/CreateUserRoleEndpoint.cs, src/UseCases/UC_UserRole/Commands/CreateUserRole.cs
feat: get compensation statuses
=> feat: create user role

src/API/Endpoints/UserRoleEndpoints/UpdateUserRoleEnpdoint.cs, src/UseCases/UC_UserRole/Commands/CreateUserRole.cs, src/UseCases/UC_UserRole/Commands/UpdateUserRole.cs
=> feat: update user role

src/API/Endpoints/UserRoleEndpoints/DeleteUserRoleEnpdoint.cs, src/UseCases/UC_UserRole/Commands/DeleteUserRole.cs
=> feat: delete user role

src/API/Endpoints/UserRoleEndpoints/GetUserRoleByIdEndpoint.cs, src/UseCases/UC_UserRole/Queries/GetUserRoleById.cs
=> feat: get user role by id

src/API/Endpoints/UserRoleEndpoints/GetUserRolesEndpoint.cs, src/UseCases/UC_UserRole/Queries/GetUserRoleById.cs, src/UseCases/UC_UserRole/Queries/GetUserRoles.cs
=> feat: get user roles

src/API/Endpoints/TransmissionTypeEndpoints/CreateTransmissionTypeEndpoint.cs, src/UseCases/UC_TransmissionType/Commands/CreateTransmissionType.cs
feat: create transmission type
=> feat: create transmission type

src/API/Endpoints/TransmissionTypeEndpoints/UpdateTransmissionTypeEndpoint.cs, src/API/Program.cs, src/API/Utils/AddAdminUser.cs, src/UseCases/UC_TransmissionType/Commands/CreateTransmissionType.cs, src/UseCases/UC_TransmissionType/Commands/UpdateTransmissionType.cs
feat: update transmission type
=> feat: update transmission type

src/API/Endpoints/TransmissionTypeEndpoints/DeleteTransmissionTypeEndpoint.cs, src/UseCases/UC_TransmissionType/Commands/DeleteTransmissionType.cs
feat: delete transmission type
=> feat: delete transmission type

src/API/Endpoints/TransmissionTypeEndpoints/GetTransmissionTypeEndpoint.cs, src/UseCases/UC_TransmissionType/Queries/GetTransmissionTypeById.cs
feat: get transmission type by id
=> feat: get transmission type by id

src/API/Endpoints/TransmissionTypeEndpoints/GetTransmissionTypesEndpoint.cs, src/UseCases/UC_TransmissionType/Queries/GetTransmissionTypes.cs
=> feat: get transmission types

src/API/Endpoints/FuelTypeEndpoints/CreateFuelTypeEndpoint.cs, src/UseCases/UC_FuelType/Commands/CreateFuelType.cs
=> feat: create fuel types

src/API/Endpoints/FuelTypeEndpoints/UpdateFuelTypeEndpoint.cs, src/UseCases/UC_FuelType/Commands/CreateFuelType.cs, src/UseCases/UC_FuelType/Commands/UpdateFuelType.cs
=> feat: update fuel types

src/API/Endpoints/FuelTypeEndpoints/GetFuelTypesEndpoint.cs, src/UseCases/UC_FuelType/Queries/GetFuelTypes.cs
=> feat: get fuel types

src/API/Endpoints/FuelTypeEndpoints/GetFuelTypeByIdEndpoint.cs, src/UseCases/UC_FuelType/Queries/GetFuelTypeById.cs
=> feat: get fuel type by id

src/API/Endpoints/ContractStatusEndpoints/CreateContractStatusEndpoint.cs, src/UseCases/UC_ContractStatus/Commands/CreateContractStatus.cs
=> feat: create contract status

src/API/Endpoints/ContractStatusEndpoints/UpdateContractStatusEndpoint.cs, src/UseCases/UC_ContractStatus/Commands/UpdateContractStatus.cs
=> feat: update contract status

src/API/Endpoints/ContractStatusEndpoints/DeleteContractStatusEndpoint.cs, src/API/Endpoints/ContractStatusEndpoints/GetContractStatusesEndpoint.cs, src/UseCases/UC_ContractStatus/Commands/DeleteContractStatus.cs, src/UseCases/UC_ContractStatus/Queries/GetContractStatuses.cs
=> feat: delete contract status

src/API/BuilderConfig.cs, src/API/Endpoints/AuthEndpoints/ValidateToken.cs, src/UseCases/Utils/TokenServices.cs
=> feat: validate token

src/API/Endpoints/AmenityEndpoints/CreateAmenityEndpoint.cs, src/API/Program.cs
- change get models to get models of a manufacturer
- fix get all models test
=> fix: change file to file collection for create amenities

src/API/Endpoints/AmenityEndpoints/CreateAmenityEndpoint.cs, src/UseCases/UC_Amenity/Commands/CreateAmenity.cs, test/UseCases.UnitTests/UC_Amenity/Commands/CreateAmenityTest.cs
[Update db](fix: check only use svg file)
=> fix: check only use svg file

src/API/Endpoints/CarEndpoints/GetCarsEndpoint.cs
fix: change lastCarId to lastId
=> fix: change lastCarId to lastId

.github/workflows/docker-image.yml
=> fix: add workflow

src/UseCases/BackgroundServices/Bookings/BookingExpiredJob.cs, src/UseCases/BackgroundServices/Bookings/BookingOverdueJob.cs, src/UseCases/UC_Booking/Commands/CancelBooking.cs, src/UseCases/UC_Booking/Commands/CompleteBooking.cs
- expired
- overdue
- complete
- cancel
=> feat: include BookingLockedBalances in booking

src/API/Program.cs
=> Revert "use cors"
